-- Disable RLS on all tables since we're using Prisma with server-side API routes
-- Security is handled at the application level, not database level

ALTER TABLE "Category" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Product" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Review" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Customer" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Loyalty" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "CartItem" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Order" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "OrderItem" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Subscriber" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "NextDrop" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "CommunityPhoto" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ExchangeRate" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "SocialHandle" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "AdminUser" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "StoreSettings" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "CommunityReview" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Notification" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "KenyaLocation" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "NotificationLog" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "EmailLog" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "SyncEvent" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "OrderReturn" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Discount" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "FAQ" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ContactMessage" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "CookieConsent" DISABLE ROW LEVEL SECURITY;
